CREATE DATABASE latter;
USE latter;

CREATE TABLE PERSONA (
ID INT AUTO_INCREMENT UNIQUE PRIMARY KEY 
, NOMBRE VARCHAR (35) NOT NULL
, APELLIDOPA VARCHAR (20) NOT NULL
, APELLIDOMA VARCHAR (20) NOT NULL
, FECHANA DATE NOT NULL
, SEXO VARCHAR (6) NOT NULL
, CURP VARCHAR (18) NOT NULL UNIQUE
, RFC VARCHAR (13) NOT NULL UNIQUE
, DIRECCION VARCHAR (50) NOT NULL 
, TELEFONO BIGINT UNIQUE NOT NULL
, EMAIL VARCHAR (30) NOT NULL UNIQUE
, NSEGURO VARCHAR (20) NOT NULL UNIQUE
);


CREATE TABLE EMPLEADO (
IDPERSONA INT NOT NULL UNIQUE
, HORAENTRADA TIME NOT NULL
, HORASALIDA TIME NOT NULL
, DESCANSO VARCHAR (9) NOT NULL
, AÑOIN YEAR NOT NULL
, FOREIGN KEY (IDPERSONA) REFERENCES PERSONA (ID)
);

CREATE TABLE CUENTAS (
IDPERSONA INT NOT NULL UNIQUE
, USUARIO VARCHAR (10) NOT NULL UNIQUE
, CONTRASEÑA VARCHAR (10)  NOT NULL
, FOREIGN KEY (IDPERSONA) REFERENCES PERSONA (ID)
);

CREATE TABLE ASISTENCIA(
IDPERSONA INT NOT NULL UNIQUE
, ENTRADA TIME NOT NULL DEFAULT '20:00:00'
, SALIDA TIME NOT NULL DEFAULT '00:00:00'
, ESTADO VARCHAR (8) NOT NULL
, FOREIGN KEY (IDPERSONA) REFERENCES PERSONA (ID)
);

CREATE TABLE REPORTES (
IDPERSONA INT NOT NULL
, FECHA DATE NOT NULL
, HORA TIME NOT NULL
, DESCPRICION VARCHAR (20) NOT NULL
, MONTO DECIMAL (6,2) NOT NULL
, FOREIGN KEY (IDPERSONA) REFERENCES PERSONA (ID)
);